---
abstract: 'Perl package wrapper for the SnpEff program'
author:
  - 'Richard J. de Borja <richard.deborja@sickkids.ca>'
build_requires:
  Test::More: '0'
configure_requires:
  Module::Build: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.133380'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: NGS-Tools-SnpEFF
provides:
  NGS::Tools::SnpEFF:
    file: lib/NGS/Tools/SnpEFF.pm
  NGS::Tools::SnpEFF::Roles::Annotate:
    file: lib/NGS/Tools/SnpEFF/Roles/Annotate.pm
resources:
  license: http://opensource.org/licenses/artistic-license-2.0.php
version: '0'
